version: '3.4'

x-restart-policy: &restart_policy
  restart: unless-stopped

services:
  app:
    << : *restart_policy
    image: buddy/repman:0.4.1
    command: >
      bash -c 'bin/console cache:clear &&
      bin/console cache:warmup &&
      bin/console d:m:m --no-interaction &&
      bin/console messenger:setup-transports --no-interaction &&
      bin/console repman:security:update-db &&
      php-fpm'
    env_file: .env.docker
    volumes:
      - app-var:/app/var

  consumer:
    << : *restart_policy
    image: buddy/repman:0.4.1
    command: ['bin/console', 'messenger:consume', 'async', '--limit=500']
    env_file: .env.docker
    volumes:
      - app-var:/app/var
    depends_on:
      - app

  cron:
    << : *restart_policy
    image: buddy/repman:0.4.1
    command: ['crond', '-f', '-L', '/dev/stdout']
    env_file: .env.docker
    volumes:
      - app-var:/app/var
      - docker-crontabs:/var/spool/cron/crontabs
    depends_on:
      - app

  nginx:
    << : *restart_policy
    image: nginx:1.17-alpine
    env_file: .env.docker
    command: ['/nginx/start.sh']
    ports:
      - ${WEB_PORT}:443
    depends_on:
      - app
    volumes:
      - app-public:/app/public
      - docker-logs-nginx/:/var/log/nginx
      - docker-nginx-scripts:/nginx
      - ${SSL_CRT_FILE}:/etc/ssl/certs/server.crt
      - ${SSL_PRV_FILE}:/etc/ssl/private/server.key

volumes:
  app-var:
    driver: local
    driver_opts:
      type: none
      device: $PWD/var
      o: bind
  app-public:
    driver: local
    driver_opts:
      type: none
      device: $PWD/public
      o: bind
  docker-logs-nginx:
    driver: local
    driver_opts:
      type: none
      device: $PWD/docker/logs/nginx
      o: bind
  docker-nginx-scripts:
    driver: local
    driver_opts:
      type: none
      device: $PWD/docker/nginx/scripts
      o: bind
  docker-crontabs:
    driver: local
    driver_opts:
      type: none
      device: $PWD/docker/crontabs
      o: bind
